<a href="https://colab.research.google.com/github/woranut11/BSC_DPDM2025/blob/main/midterm_663020294-7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### อ่านไฟล์ทั้งหมด และอธิบายความหมายของแต่ละคอลัมน์

In [3]:
station = pd.read_csv('/content/drive/MyDrive/midterm.2/Stations in the model_HII.csv')
station.head()

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

In [32]:
station.isnull().sum()

Node    0
Lat     0
Long    0
dtype: int64

In [33]:
station.shape

(385, 3)

In [4]:
station.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    385 non-null    object
 1   Lat     385 non-null    float64
 2   Long    385 non-null    float64
dtypes: float64(2), object(1)
memory usage: 9.2+ KB

In [5]:
station.head()

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

จากข้อมูลที่แสดง:  
*   **Node**: คาดว่าเป็นรหัสหรือชื่อประจำสถานี  
*   **Lat**: Latitude (ละติจูด) แสดงพิกัดทางภูมิศาสตร์ของสถานีในแนวเหนือ-ใต้  
*   **Long**: Longitude (ลองจิจูด) แสดงพิกัดทางภูมิศาสตร์ของสถานีในแนวตะวันออก-ตะวันตก

In [6]:
hill_daily_rain = pd.read_csv('/content/drive/MyDrive/midterm.2/hii_daily_rain.csv')
hill_daily_rain.head()

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

In [7]:
hill_daily_rain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768463 entries, 0 to 3768462
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  object
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
dtypes: float64(3), object(10)
memory usage: 373.8+ MB

In [8]:
hill_daily_rain.head()

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

จากข้อมูลที่แสดงใน `hill_daily_rain`:
*   **station_code**: รหัสประจำสถานีตรวจวัด.
*   **measure_datetime**: วันที่และเวลาที่มีการตรวจวัดข้อมูล.
*   **data**: ค่าข้อมูลที่ตรวจวัดได้ (ในกรณีนี้คือปริมาณน้ำฝน).
*   **station_name**: ชื่อของสถานีตรวจวัด.
*   **latitude**: ละติจูดของสถานีตรวจวัด.
*   **longitude**: ลองจิจูดของสถานีตรวจวัด.
*   **quality_flag**: แฟล็กที่ระบุคุณภาพของข้อมูล.
*   **basin**: ชื่อลุ่มน้ำที่สถานีตั้งอยู่.
*   **sub_basin**: ชื่อลุ่มน้ำย่อย.
*   **tambon**: ตำบลที่ตั้งของสถานี.
*   **amphoe**: อำเภอที่ตั้งของสถานี.
*   **province**: จังหวัดที่ตั้งของสถานี.
*   **data_type**: ชนิดของข้อมูลที่ตรวจวัด (ในกรณีนี้คือ 'rainfall_daily').

In [9]:
Y_monthly_rain = pd.read_csv('/content/drive/MyDrive/midterm.2/Y_monthly_rain_HII_operation.csv')
Y_monthly_rain.head()

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

In [10]:
Y_monthly_rain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    18 non-null     object
 1   rain    18 non-null     float64
 2   month   18 non-null     int64
 3   year    18 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 708.0+ bytes

In [11]:
Y_monthly_rain.head()

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

จากข้อมูลที่แสดงใน `Y_monthly_rain`:
*   **Node**: รหัสประจำสถานี
*   **rain**: ปริมาณน้ำฝน (หน่วย: มิลลิเมตร)
*   **month**: เดือนของปี
*   **year**: ปี

### กรองข้อมูลให้เหลือเฉพาะสถานีใน stations in the model_HIII.csv

### ข้อมูล `hill_daily_rain` ก่อนกรอง (5 แถวแรก)

In [22]:
display(hill_daily_rain.head())

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

### ข้อมูล `hill_daily_rain` หลังกรอง (5 แถวแรก)

In [34]:
display(hill_daily_rain_filtered.head())

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
3488,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3489,ACRU,2012-01-06 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3490,ACRU,2012-01-07 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3491,ACRU,2012-01-08 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3492,ACRU,2012-01-09 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

### กรองข้อมูล `hill_daily_rain` ให้เหลือเฉพาะสถานีที่อยู่ใน `station` DataFrame

In [25]:
import numpy as np

# Get unique station codes from 'station' DataFrame
station_nodes = station['Node'].unique()

# Display the number of unique stations in hill_daily_rain before filtering
initial_unique_stations = hill_daily_rain['station_code'].nunique()
print(f"จำนวนสถานีที่ไม่ซ้ำกันใน hill_daily_rain ก่อนกรอง: {initial_unique_stations} สถานี")

# Filter hill_daily_rain to include only stations present in station_nodes
hill_daily_rain_filtered = hill_daily_rain[hill_daily_rain['station_code'].isin(station_nodes)]

# Display the number of unique stations in hill_daily_rain after filtering
filtered_unique_stations = hill_daily_rain_filtered['station_code'].nunique()
print(f"จำนวนสถานีที่ไม่ซ้ำกันใน hill_daily_rain หลังกรอง: {filtered_unique_stations} สถานี")

# Display the head of the filtered DataFrame
print("\nข้อมูล hill_daily_rain ที่ถูกกรองแล้ว (5 แถวแรก):")
display(hill_daily_rain_filtered.head())

จำนวนสถานีที่ไม่ซ้ำกันใน hill_daily_rain ก่อนกรอง: 1387 สถานี
จำนวนสถานีที่ไม่ซ้ำกันใน hill_daily_rain หลังกรอง: 385 สถานี

ข้อมูล hill_daily_rain ที่ถูกกรองแล้ว (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
3488,ACRU,2012-01-01 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3489,ACRU,2012-01-06 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3490,ACRU,2012-01-07 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3491,ACRU,2012-01-08 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3492,ACRU,2012-01-09 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

## ระบุข้อมูลสูญหาย(record ที่หายไป) ของแต่ละสถานี แสดงจำนวน และสัดส่วน

### ขั้นตอนที่ 1: ระบุช่วงวันที่สำหรับแต่ละสถานี

**เหตุผล:** หลังจากแปลงคอลัมน์ 'measure_datetime' เป็นรูปแบบ datetime แล้ว ขั้นตอนต่อไปคือการกำหนดวันที่เริ่มและสิ้นสุดการสังเกตสำหรับแต่ละสถานี สิ่งนี้สำคัญอย่างยิ่งในการกำหนดระยะเวลาที่สมบูรณ์ที่แต่ละสถานีควรมีข้อมูลรายวัน

In [27]:
date_ranges = hill_daily_rain_filtered.groupby('station_code')['measure_datetime'].agg(['min', 'max'])
display(date_ranges.head())

                                   min                       max
station_code
ACRU         2012-01-01 00:00:00+00:00 2024-11-28 17:00:00+00:00
BBHN         2012-01-01 00:00:00+00:00 2024-11-28 17:00:00+00:00
BBUA         2012-01-01 00:00:00+00:00 2024-11-28 17:00:00+00:00
BCNG         2012-01-01 00:00:00+00:00 2024-11-28 17:00:00+00:00
BDAR         2012-01-01 00:00:00+00:00 2024-11-28 17:00:00+00:00

In [26]:
hill_daily_rain_filtered = hill_daily_rain_filtered.copy()
hill_daily_rain_filtered['measure_datetime'] = pd.to_datetime(hill_daily_rain_filtered['measure_datetime'], utc=True)
print("ประเภทข้อมูลหลังจากแปลง 'measure_datetime' เป็น datetime objects:")
hill_daily_rain_filtered.info()
print("\n5 แถวแรกของ hill_daily_rain_filtered หลังการแปลง:")
display(hill_daily_rain_filtered.head())

ประเภทข้อมูลหลังจากแปลง 'measure_datetime' เป็น datetime objects:
<class 'pandas.core.frame.DataFrame'>
Index: 1662282 entries, 3488 to 3768169
Data columns (total 13 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   station_code      1662282 non-null  object
 1   measure_datetime  1662282 non-null  datetime64[ns, UTC]
 2   data              1662266 non-null  float64
 3   station_name      1662282 non-null  object
 4   latitude          1662282 non-null  float64
 5   longitude         1662282 non-null  float64
 6   quality_flag      1662282 non-null  object
 7   basin             1662282 non-null  object
 8   sub_basin         1662282 non-null  object
 9   tambon            1662282 non-null  object
 10  amphoe            1662282 non-null  object
 11  province          1662282 non-null  object
 12  data_type         1662282 non-null  object
dtypes: datetime64[ns, UTC](1), float64(3), object(9)
memory usage: 177.6+ MB

5 แถวแรกของ hill_daily_rain_filtered หลังการแปลง:

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
3488,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3489,ACRU,2012-01-06 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3490,ACRU,2012-01-07 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3491,ACRU,2012-01-08 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3492,ACRU,2012-01-09 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

### ขั้นตอนที่ 2: คำนวณจำนวนวันที่คาดว่าจะมีข้อมูลสำหรับแต่ละสถานี

**เหตุผล:** การคำนวณจำนวนวันที่คาดว่าจะมีข้อมูลในแต่ละสถานี (จากวันที่เริ่มต้นถึงวันที่สิ้นสุด) เป็นสิ่งสำคัญในการหาจำนวนข้อมูลที่ขาดหายไป โดยการนำจำนวนวันที่คาดหวังนี้ไปเปรียบเทียบกับจำนวนข้อมูลจริงที่มีอยู่

In [28]:
date_ranges['expected_days'] = (date_ranges['max'] - date_ranges['min']).dt.days + 1
display(date_ranges.head())

,min,max,expected_days
station_code,,,
ACRU,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716
BBHN,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716
BBUA,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716
BCNG,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716
BDAR,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716



```
# This is formatted as code
```

### ขั้นตอนที่ 3: นับจำนวนบันทึกข้อมูลจริงสำหรับแต่ละสถานี

**เหตุผล:** เพื่อคำนวณจำนวนบันทึกข้อมูลที่หายไป จำเป็นต้องทราบจำนวนบันทึกข้อมูลจริงที่มีอยู่สำหรับแต่ละสถานี การนับจำนวนบันทึกข้อมูลจริงนี้จะนำไปเปรียบเทียบกับจำนวนวันที่คาดหวังเพื่อหาความสมบูรณ์ของข้อมูล

In [29]:
actual_records = hill_daily_rain_filtered.groupby('station_code').size().reset_index(name='actual_records')
display(actual_records.head())

  station_code  actual_records
0         ACRU            4501
1         BBHN            4393
2         BBUA            4605
3         BCNG            4626
4         BDAR            4376

### ขั้นตอนที่ 4: คำนวณบันทึกที่หายไปและสัดส่วนความสมบูรณ์ของข้อมูล

**เหตุผล:** หลังจากได้ข้อมูลจำนวนวันที่คาดหวังและจำนวนบันทึกข้อมูลจริงของแต่ละสถานีแล้ว ขั้นตอนนี้จะทำการรวมข้อมูลทั้งสองเข้าด้วยกันเพื่อคำนวณจำนวนข้อมูลที่หายไปและแสดงเป็นสัดส่วนร้อยละความสมบูรณ์ของข้อมูล

In [30]:
completeness_analysis = pd.merge(date_ranges, actual_records, on='station_code', how='left')
completeness_analysis['missing_records'] = completeness_analysis['expected_days'] - completeness_analysis['actual_records']
completeness_analysis['completeness_percentage'] = (completeness_analysis['actual_records'] / completeness_analysis['expected_days']) * 100

print("ผลการวิเคราะห์ความสมบูรณ์ของข้อมูลปริมาณน้ำฝนรายวัน (5 แถวแรก):\n")
display(completeness_analysis.head())

ผลการวิเคราะห์ความสมบูรณ์ของข้อมูลปริมาณน้ำฝนรายวัน (5 แถวแรก):

,station_code,min,max,expected_days,actual_records,missing_records,completeness_percentage
0,ACRU,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4501,215,95.441052
1,BBHN,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4393,323,93.150975
2,BBUA,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4605,111,97.646310
3,BCNG,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4626,90,98.091603
4,BDAR,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4376,340,92.790500

### ขั้นตอนที่ 5: แสดงผลสรุปความสมบูรณ์ของข้อมูล

**เหตุผล:** เพื่อให้เห็นภาพรวมของข้อมูลที่หายไปได้อย่างชัดเจน การแสดงสถานีที่มีสัดส่วนความสมบูรณ์ของข้อมูลต่ำที่สุดและสูงที่สุดจะช่วยให้สามารถระบุสถานีที่ต้องการการตรวจสอบเพิ่มเติมได้ง่ายขึ้น

In [31]:
completeness_analysis_sorted = completeness_analysis.sort_values(by='completeness_percentage', ascending=True)
print("ผลการวิเคราะห์ความสมบูรณ์ของข้อมูลปริมาณน้ำฝนรายวัน (เรียงตามสัดส่วนความสมบูรณ์จากน้อยไปมาก, 5 แถวแรก):\n")
display(completeness_analysis_sorted.head())

print("\nผลการวิเคราะห์ความสมบูรณ์ของข้อมูลปริมาณน้ำฝนรายวัน (เรียงตามสัดส่วนความสมบูรณ์จากน้อยไปมาก, 5 แถวสุดท้าย):\n")
display(completeness_analysis_sorted.tail())

ผลการวิเคราะห์ความสมบูรณ์ของข้อมูลปริมาณน้ำฝนรายวัน (เรียงตามสัดส่วนความสมบูรณ์จากน้อยไปมาก, 5 แถวแรก):

,station_code,min,max,expected_days,actual_records,missing_records,completeness_percentage
46,BPLA,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,3755,961,79.622561
283,STH005,2012-10-31 00:00:00+00:00,2024-11-28 17:00:00+00:00,4412,3636,776,82.411605
10,BHMN,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,3895,821,82.591179
128,KHHM,2012-01-13 00:00:00+00:00,2024-11-28 17:00:00+00:00,4704,3907,797,83.056973
16,BKHN,2012-01-25 00:00:00+00:00,2024-11-28 17:00:00+00:00,4692,3914,778,83.418585

ผลการวิเคราะห์ความสมบูรณ์ของข้อมูลปริมาณน้ำฝนรายวัน (เรียงตามสัดส่วนความสมบูรณ์จากน้อยไปมาก, 5 แถวสุดท้าย):

,station_code,min,max,expected_days,actual_records,missing_records,completeness_percentage
7,BDLH,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4701,15,99.681934
313,THNG,2015-04-09 00:00:00+00:00,2024-11-28 17:00:00+00:00,3522,3512,10,99.716070
137,KOLO,2012-03-12 00:00:00+00:00,2024-11-28 17:00:00+00:00,4645,4634,11,99.763186
78,CHNA,2012-01-01 00:00:00+00:00,2024-11-28 17:00:00+00:00,4716,4707,9,99.809160
71,CHI012,2013-03-10 00:00:00+00:00,2024-11-28 17:00:00+00:00,4282,4274,8,99.813171

### คัดสถานีที่มีข้อมูลสูญหาย >= 20% ออก แสดงรายชื่อสถานีที่ถูกคัดออก และจำนวนที่เหลือ

In [36]:
# Identify stations with completeness percentage less than 80% (i.e., missing records >= 20%)
stations_to_drop = completeness_analysis[completeness_analysis['completeness_percentage'] < 80]

# Display the names of stations to be dropped
print("รายชื่อสถานีที่มีข้อมูลสูญหาย >= 20% ที่จะถูกคัดออก:")
display(stations_to_drop[['station_code', 'completeness_percentage']])

# Get the number of stations to be dropped
num_stations_to_drop = len(stations_to_drop)
print(f"\nจำนวนสถานีที่จะถูกคัดออก: {num_stations_to_drop} สถานี")

# Get the station codes of those to be dropped
dropped_station_codes = stations_to_drop['station_code'].tolist()

# Filter hill_daily_rain_filtered to keep only stations that are NOT in the dropped list
hill_daily_rain_cleaned = hill_daily_rain_filtered[~hill_daily_rain_filtered['station_code'].isin(dropped_station_codes)]

# Update completeness_analysis as well to reflect the removed stations
completeness_analysis_cleaned = completeness_analysis[~completeness_analysis['station_code'].isin(dropped_station_codes)]

# Display the number of remaining stations
num_remaining_stations = hill_daily_rain_cleaned['station_code'].nunique()
print(f"\nจำนวนสถานีที่เหลือหลังจากคัดออก: {num_remaining_stations} สถานี")

print("\nข้อมูล hill_daily_rain_cleaned (5 แถวแรก): ")
display(hill_daily_rain_cleaned.head())

รายชื่อสถานีที่มีข้อมูลสูญหาย >= 20% ที่จะถูกคัดออก:

   station_code  completeness_percentage
46         BPLA                79.622561

จำนวนสถานีที่จะถูกคัดออก: 1 สถานี

จำนวนสถานีที่เหลือหลังจากคัดออก: 384 สถานี

ข้อมูล hill_daily_rain_cleaned (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
3488,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3489,ACRU,2012-01-06 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3490,ACRU,2012-01-07 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3491,ACRU,2012-01-08 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3492,ACRU,2012-01-09 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

# Task
เติมข้อมูลที่หายไปของปริมาณน้ำฝนรายวันใน `hill_daily_rain_cleaned` โดยการสร้างคอลัมน์ 'day_of_year', สร้างช่วงวันที่สมบูรณ์สำหรับแต่ละสถานี, ระบุบันทึกที่ขาดหายไป, คำนวณค่ามัธยฐานปริมาณน้ำฝนตามวันในรอบปีและสถานี, เติมค่าที่ขาดหายไปด้วยค่ามัธยฐานที่คำนวณได้ และตรวจสอบความสมบูรณ์ของข้อมูลอีกครั้งเพื่อยืนยันว่าไม่มีบันทึกที่ขาดหายไป

## เตรียมข้อมูลสำหรับการเติมค่า

### Subtask:
ตรวจสอบให้แน่ใจว่าคอลัมน์ 'measure_datetime' ใน `hill_daily_rain_cleaned` เป็นรูปแบบ datetime และเพิ่มคอลัมน์ 'day_of_year' ซึ่งจะใช้ในการคำนวณค่ามัธยฐาน

**Reasoning**:
First, I'll ensure the 'measure_datetime' column in `hill_daily_rain_cleaned` is of datetime type, handling potential timezone issues to prepare it for date extraction. Then, I'll extract the day of the year from this column and store it in a new 'day_of_year' column, which is essential for calculating median values.

In [37]:
import pandas as pd

# Ensure 'measure_datetime' is a datetime object
# Using errors='coerce' will turn unparseable dates into NaT (Not a Time)
hill_daily_rain_cleaned['measure_datetime'] = pd.to_datetime(hill_daily_rain_cleaned['measure_datetime'], errors='coerce', utc=True)

# Drop rows where 'measure_datetime' conversion failed (if any)
hill_daily_rain_cleaned.dropna(subset=['measure_datetime'], inplace=True)

# Create 'day_of_year' column
hill_daily_rain_cleaned['day_of_year'] = hill_daily_rain_cleaned['measure_datetime'].dt.dayofyear

print("ข้อมูล 'hill_daily_rain_cleaned' หลังตรวจสอบและเพิ่มคอลัมน์ 'day_of_year' (5 แถวแรก):")
display(hill_daily_rain_cleaned.head())
print("ประเภทข้อมูลของคอลัมน์ 'measure_datetime' และ 'day_of_year':")
print(hill_daily_rain_cleaned[['measure_datetime', 'day_of_year']].dtypes)

/tmp/ipython-input-3109567648.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hill_daily_rain_cleaned['measure_datetime'] = pd.to_datetime(hill_daily_rain_cleaned['measure_datetime'], errors='coerce', utc=True)

ข้อมูล 'hill_daily_rain_cleaned' หลังตรวจสอบและเพิ่มคอลัมน์ 'day_of_year' (5 แถวแรก):

/tmp/ipython-input-3109567648.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hill_daily_rain_cleaned.dropna(subset=['measure_datetime'], inplace=True)
/tmp/ipython-input-3109567648.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hill_daily_rain_cleaned['day_of_year'] = hill_daily_rain_cleaned['measure_datetime'].dt.dayofyear

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
3488,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
3489,ACRU,2012-01-06 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,6
3490,ACRU,2012-01-07 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,7
3491,ACRU,2012-01-08 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,8
3492,ACRU,2012-01-09 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,9

ประเภทข้อมูลของคอลัมน์ 'measure_datetime' และ 'day_of_year':
measure_datetime    datetime64[ns, UTC]
day_of_year                       int32
dtype: object

**Reasoning**:
The previous code produced a `SettingWithCopyWarning` because operations were being performed on what pandas identified as a slice of a DataFrame. To ensure modifications are applied correctly and to suppress the warning, I will explicitly create a copy of `hill_daily_rain_cleaned` at the start of the cell.

In [52]:
import pandas as pd

# Create an explicit copy to avoid SettingWithCopyWarning
hill_daily_rain_cleaned = hill_daily_rain_cleaned.copy()

# Ensure 'measure_datetime' is a datetime object
# Using errors='coerce' will turn unparseable dates into NaT (Not a Time)
hill_daily_rain_cleaned['measure_datetime'] = pd.to_datetime(hill_daily_rain_cleaned['measure_datetime'], errors='coerce', utc=True)

# Drop rows where 'measure_datetime' conversion failed (if any)
hill_daily_rain_cleaned.dropna(subset=['measure_datetime'], inplace=True)

# Create 'day_of_year' column
hill_daily_rain_cleaned['day_of_year'] = hill_daily_rain_cleaned['measure_datetime'].dt.dayofyear

print("ข้อมูล 'hill_daily_rain_cleaned' หลังตรวจสอบและเพิ่มคอลัมน์ 'day_of_year' (5 แถวแรก):")
display(hill_daily_rain_cleaned.head())
print("ประเภทข้อมูลของคอลัมน์ 'measure_datetime' และ 'day_of_year':")
print(hill_daily_rain_cleaned[['measure_datetime', 'day_of_year']].dtypes)

ข้อมูล 'hill_daily_rain_cleaned' หลังตรวจสอบและเพิ่มคอลัมน์ 'day_of_year' (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,...,tambon,amphoe,province,data_type,day_of_year
3488,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,...,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
3489,ACRU,2012-01-06 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,...,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,6
3490,ACRU,2012-01-07 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,...,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,7
3491,ACRU,2012-01-08 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,...,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,8
3492,ACRU,2012-01-09 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,...,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,9

ประเภทข้อมูลของคอลัมน์ 'measure_datetime' และ 'day_of_year':
measure_datetime    datetime64[ns, UTC]
day_of_year                       int32
dtype: object

**Reasoning**:
The previous code had a typo, using `hill_daily_cleaned` instead of `hill_daily_rain_cleaned` when creating the 'day_of_year' column, which caused a `NameError`. I will correct this typo to ensure the column is added to the intended DataFrame.

In [53]:
import pandas as pd

# Create an explicit copy to avoid SettingWithCopyWarning
hill_daily_rain_cleaned = hill_daily_rain_cleaned.copy()

# Ensure 'measure_datetime' is a datetime object
# Using errors='coerce' will turn unparseable dates into NaT (Not a Time)
hill_daily_rain_cleaned['measure_datetime'] = pd.to_datetime(hill_daily_rain_cleaned['measure_datetime'], errors='coerce', utc=True)

# Drop rows where 'measure_datetime' conversion failed (if any)
hill_daily_rain_cleaned.dropna(subset=['measure_datetime'], inplace=True)

# Create 'day_of_year' column
hill_daily_rain_cleaned['day_of_year'] = hill_daily_rain_cleaned['measure_datetime'].dt.dayofyear

print("ข้อมูล 'hill_daily_rain_cleaned' หลังตรวจสอบและเพิ่มคอลัมน์ 'day_of_year' (5 แถวแรก):")
display(hill_daily_rain_cleaned.head())
print("ประเภทข้อมูลของคอลัมน์ 'measure_datetime' และ 'day_of_year':")
print(hill_daily_rain_cleaned[['measure_datetime', 'day_of_year']].dtypes)

ข้อมูล 'hill_daily_rain_cleaned' หลังตรวจสอบและเพิ่มคอลัมน์ 'day_of_year' (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
3488,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
3489,ACRU,2012-01-06 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,6
3490,ACRU,2012-01-07 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,7
3491,ACRU,2012-01-08 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,8
3492,ACRU,2012-01-09 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,9

ประเภทข้อมูลของคอลัมน์ 'measure_datetime' และ 'day_of_year':
measure_datetime    datetime64[ns, UTC]
day_of_year                       int32
dtype: object

## สร้างชุดข้อมูลวันที่มีอยู่จริงสำหรับแต่ละสถานี

### Subtask:
สำหรับแต่ละสถานี ให้สร้าง DataFrame ที่มีวันที่ทั้งหมดตั้งแต่ 'measure_datetime' ต่ำสุดถึงสูงสุดของสถานีนั้น เพื่อใช้เป็นฐานในการระบุว่าวันไหนที่ขาดหายไป

In [54]:
date_ranges_per_station = hill_daily_rain_cleaned.groupby('station_code')['measure_datetime'].agg(['min', 'max'])

full_date_records = []
for station_code, row in date_ranges_per_station.iterrows():
    min_date = row['min']
    max_date = row['max']
    if pd.isna(min_date) or pd.isna(max_date):
        # Skip if min or max date is NaN (shouldn't happen with proper filtering but good practice)
        continue

    # Generate a full date range for the current station
    dates = pd.date_range(start=min_date, end=max_date, freq='D')

    # Append records for this station to the list
    for date in dates:
        full_date_records.append({'station_code': station_code, 'measure_datetime': date})

# Convert the list of dictionaries to a DataFrame
full_date_range = pd.DataFrame(full_date_records)

print("ข้อมูล 'full_date_range' ที่สร้างขึ้น (5 แถวแรก):")
display(full_date_range.head())
print("จำนวนแถวทั้งหมดใน full_date_range:", len(full_date_range))
print("ประเภทข้อมูลของ full_date_range:")
full_date_range.info()

ข้อมูล 'full_date_range' ที่สร้างขึ้น (5 แถวแรก):

  station_code          measure_datetime
0         ACRU 2012-01-01 00:00:00+00:00
1         ACRU 2012-01-02 00:00:00+00:00
2         ACRU 2012-01-03 00:00:00+00:00
3         ACRU 2012-01-04 00:00:00+00:00
4         ACRU 2012-01-05 00:00:00+00:00

จำนวนแถวทั้งหมดใน full_date_range: 1759835
ประเภทข้อมูลของ full_date_range:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1759835 entries, 0 to 1759834
Data columns (total 2 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 26.9+ MB

## สร้างชุดข้อมูลวันที่มีอยู่จริงสำหรับแต่ละสถานี

### Subtask:
สำหรับแต่ละสถานี ให้สร้าง DataFrame ที่มีวันที่ทั้งหมดตั้งแต่ 'measure_datetime' ต่ำสุดถึงสูงสุดของสถานีนั้น เพื่อใช้เป็นฐานในการระบุว่าวันไหนที่ขาดหายไป

In [55]:
date_ranges_per_station = hill_daily_rain_cleaned.groupby('station_code')['measure_datetime'].agg(['min', 'max'])

full_date_records = []
for station_code, row in date_ranges_per_station.iterrows():
    min_date = row['min']
    max_date = row['max']
    if pd.isna(min_date) or pd.isna(max_date):
        # Skip if min or max date is NaN (shouldn't happen with proper filtering but good practice)
        continue

    # Generate a full date range for the current station
    dates = pd.date_range(start=min_date, end=max_date, freq='D')

    # Append records for this station to the list
    for date in dates:
        full_date_records.append({'station_code': station_code, 'measure_datetime': date})

# Convert the list of dictionaries to a DataFrame
full_date_range = pd.DataFrame(full_date_records)

print("ข้อมูล 'full_date_range' ที่สร้างขึ้น (5 แถวแรก):")
display(full_date_range.head())
print("จำนวนแถวทั้งหมดใน full_date_range:", len(full_date_range))
print("ประเภทข้อมูลของ full_date_range:")
full_date_range.info()

ข้อมูล 'full_date_range' ที่สร้างขึ้น (5 แถวแรก):

  station_code          measure_datetime
0         ACRU 2012-01-01 00:00:00+00:00
1         ACRU 2012-01-02 00:00:00+00:00
2         ACRU 2012-01-03 00:00:00+00:00
3         ACRU 2012-01-04 00:00:00+00:00
4         ACRU 2012-01-05 00:00:00+00:00

จำนวนแถวทั้งหมดใน full_date_range: 1759835
ประเภทข้อมูลของ full_date_range:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1759835 entries, 0 to 1759834
Data columns (total 2 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 26.9+ MB

**Reasoning**:
Now that a complete date range has been generated for each station, the next step is to merge this `full_date_range` with the actual `hill_daily_rain_cleaned` data. This merge will highlight which dates are missing from the actual data for each station, which can then be identified as the missing records.

In [56]:
merged_df = pd.merge(full_date_range, hill_daily_rain_cleaned, on=['station_code', 'measure_datetime'], how='left')

missing_records_df = merged_df[merged_df['data'].isnull()].copy()

print("ข้อมูลบันทึกที่หายไป (5 แถวแรก):")
display(missing_records_df.head())
print("จำนวนบันทึกที่หายไปทั้งหมด:", len(missing_records_df))

# Ensure 'day_of_year' is available in the missing_records_df for later use
missing_records_df['day_of_year'] = missing_records_df['measure_datetime'].dt.dayofyear

print("ประเภทข้อมูลของ missing_records_df หลังจากเพิ่ม 'day_of_year':")
missing_records_df.info()

ข้อมูลบันทึกที่หายไป (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
1,ACRU,2012-01-02 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACRU,2012-01-03 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACRU,2012-01-04 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACRU,2012-01-05 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,ACRU,2012-10-31 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

จำนวนบันทึกที่หายไปทั้งหมด: 345724
ประเภทข้อมูลของ missing_records_df หลังจากเพิ่ม 'day_of_year':
<class 'pandas.core.frame.DataFrame'>
Index: 345724 entries, 1 to 1759834
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   station_code      345724 non-null  object
 1   measure_datetime  345724 non-null  datetime64[ns, UTC]
 2   data              0 non-null       float64
 3   station_name      14 non-null      object
 4   latitude          14 non-null      float64
 5   longitude         14 non-null      float64
 6   quality_flag      14 non-null      object
 7   basin             14 non-null      object
 8   sub_basin         14 non-null      object
 9   tambon            14 non-null      object
 10  amphoe            14 non-null      object
 11  province          14 non-null      object
 12  data_type         14 non-null      object
 13  day_of_year       345724 non-null  int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 38.2+ MB

**Reasoning**:
As outlined in the subtask, the next step is to calculate the median rainfall for each station and each day of the year from the `hill_daily_rain_cleaned` DataFrame. This will provide the imputation values for the missing records.

In [57]:
median_rainfall_by_day = hill_daily_rain_cleaned.groupby(['station_code', 'day_of_year'])['data'].median().reset_index()

print("ค่ามัธยฐานปริมาณน้ำฝนตามวันในรอบปีและสถานี (5 แถวแรก):\n")
display(median_rainfall_by_day.head())
print("ข้อมูล 'median_rainfall_by_day':")
median_rainfall_by_day.info()

ค่ามัธยฐานปริมาณน้ำฝนตามวันในรอบปีและสถานี (5 แถวแรก):

  station_code  day_of_year  data
0         ACRU            1   0.0
1         ACRU            2   0.0
2         ACRU            3   0.0
3         ACRU            4   0.0
4         ACRU            5   0.0

ข้อมูล 'median_rainfall_by_day':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140544 entries, 0 to 140543
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   station_code  140544 non-null  object
 1   day_of_year   140544 non-null  int32
 2   data          140544 non-null  float64
dtypes: float64(1), int32(1), object(1)
memory usage: 2.7+ MB

## คำนวณค่ามัธยฐานปริมาณน้ำฝนตามวันในรอบปีและสถานี

### Subtask:
คำนวณค่ามัธยฐานปริมาณน้ำฝน (`data` column) สำหรับแต่ละ 'station_code' และ 'day_of_year' จาก `hill_daily_rain_cleaned` เพื่อใช้เป็นค่าเติมเต็มสำหรับข้อมูลที่ขาดหายไป

## ตรวจสอบความสมบูรณ์ของข้อมูลอีกครั้ง

### Subtask:
หลังจากเติมค่าที่หายไปแล้ว ให้ทำการตรวจสอบความสมบูรณ์ของข้อมูลอีกครั้ง เพื่อยืนยันว่าไม่มี record ที่หายไปแล้ว และความสมบูรณ์ของข้อมูลเป็น 100%

In [66]:
print("ตรวจสอบจำนวนค่าว่างในคอลัมน์ 'data' ของ combined_df หลังเติมค่าทั้งหมด:")
print(combined_df['data'].isnull().sum())

print("\nจำนวนสถานีที่ไม่ซ้ำกันใน combined_df:")
print(combined_df['station_code'].nunique())

print("\nจำนวนแถวทั้งหมดใน combined_df หลังจากเติมค่า:")
print(len(combined_df))

ตรวจสอบจำนวนค่าว่างในคอลัมน์ 'data' ของ combined_df หลังเติมค่าทั้งหมด:
0

จำนวนสถานีที่ไม่ซ้ำกันใน combined_df:
384

จำนวนแถวทั้งหมดใน combined_df หลังจากเติมค่า:
2004251

In [65]:
import numpy as np

# Calculate the global median rainfall for each day of the year
global_daily_median = combined_df.groupby('day_of_year')['data'].median().reset_index()
global_daily_median.rename(columns={'data': 'global_median_data'}, inplace=True)

# Merge global median back to combined_df for imputation
combined_df = pd.merge(combined_df, global_daily_median, on='day_of_year', how='left')

# Fill remaining NaN values in 'data' column with the global_median_data
combined_df['data'] = combined_df['data'].fillna(combined_df['global_median_data'])

# Drop the temporary 'global_median_data' column
combined_df.drop(columns=['global_median_data'], inplace=True)

print("ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวแรก):\n")
display(combined_df.head())
print("ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวสุดท้าย):\n")
display(combined_df.tail())
print("ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled หลังเติมเต็มอีกครั้ง:\n")
print(combined_df['data'].isnull().sum())
print("ประเภทข้อมูลของ hill_daily_rain_filled:\n")
combined_df.info()

ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
0,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
1,ACRU,2012-01-02 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2
2,ACRU,2012-01-03 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,3
3,ACRU,2012-01-04 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,4
4,ACRU,2012-01-05 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,5

ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวสุดท้าย):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
2004246,YOM012,2024-11-26 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,331
2004247,YOM012,2024-11-27 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004248,YOM012,2024-11-27 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004249,YOM012,2024-11-28 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333
2004250,YOM012,2024-11-28 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333

ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled หลังเติมเต็มอีกครั้ง:

0
ประเภทข้อมูลของ hill_daily_rain_filled:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004251 entries, 0 to 2004250
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  day_of_year       int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 206.4+ MB

In [64]:
combined_df = pd.concat([hill_daily_rain_cleaned, missing_records_filled], ignore_index=True)

# Sort the combined DataFrame to ensure chronological order for each station
combined_df.sort_values(by=['station_code', 'measure_datetime'], inplace=True)

# Reset index after sorting
combined_df.reset_index(drop=True, inplace=True)

# Ensure 'day_of_year' is present in the final combined dataframe
combined_df['day_of_year'] = combined_df['measure_datetime'].dt.dayofyear

print("ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวแรก):\n")
display(combined_df.head())
print("ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวสุดท้าย):\n")
display(combined_df.tail())
print("ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled:\n")
print(combined_df['data'].isnull().sum())
print("ประเภทข้อมูลของ hill_daily_rain_filled:\n")
combined_df.info()

ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
0,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
1,ACRU,2012-01-02 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2
2,ACRU,2012-01-03 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,3
3,ACRU,2012-01-04 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,4
4,ACRU,2012-01-05 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,5

ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวสุดท้าย):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
2004246,YOM012,2024-11-26 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,331
2004247,YOM012,2024-11-27 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004248,YOM012,2024-11-27 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004249,YOM012,2024-11-28 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333
2004250,YOM012,2024-11-28 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333

ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled:

16
ประเภทข้อมูลของ hill_daily_rain_filled:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004251 entries, 0 to 2004250
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  day_of_year       int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 206.4+ MB

In [60]:
median_rainfall_by_day = hill_daily_rain_cleaned.groupby(['station_code', 'day_of_year'])['data'].median().reset_index()

print("ค่ามัธยฐานปริมาณน้ำฝนตามวันในรอบปีและสถานี (5 แถวแรก):\n")
display(median_rainfall_by_day.head())
print("ข้อมูล 'median_rainfall_by_day':")
median_rainfall_by_day.info()

ค่ามัธยฐานปริมาณน้ำฝนตามวันในรอบปีและสถานี (5 แถวแรก):

  station_code  day_of_year  data
0         ACRU            1   0.0
1         ACRU            2   0.0
2         ACRU            3   0.0
3         ACRU            4   0.0
4         ACRU            5   0.0

ข้อมูล 'median_rainfall_by_day':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140544 entries, 0 to 140543
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   station_code  140544 non-null  object
 1   day_of_year   140544 non-null  int32
 2   data          140544 non-null  float64
dtypes: float64(1), int32(1), object(1)
memory usage: 2.7+ MB

In [61]:
merged_df = pd.merge(full_date_range, hill_daily_rain_cleaned, on=['station_code', 'measure_datetime'], how='left')

missing_records_df = merged_df[merged_df['data'].isnull()].copy()

print("ข้อมูลบันทึกที่หายไป (5 แถวแรก):")
display(missing_records_df.head())
print("จำนวนบันทึกที่หายไปทั้งหมด:", len(missing_records_df))

# Ensure 'day_of_year' is available in the missing_records_df for later use
missing_records_df['day_of_year'] = missing_records_df['measure_datetime'].dt.dayofyear

print("ประเภทข้อมูลของ missing_records_df หลังจากเพิ่ม 'day_of_year':")
missing_records_df.info()

ข้อมูลบันทึกที่หายไป (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
1,ACRU,2012-01-02 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACRU,2012-01-03 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACRU,2012-01-04 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACRU,2012-01-05 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,ACRU,2012-10-31 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

จำนวนบันทึกที่หายไปทั้งหมด: 345724
ประเภทข้อมูลของ missing_records_df หลังจากเพิ่ม 'day_of_year':
<class 'pandas.core.frame.DataFrame'>
Index: 345724 entries, 1 to 1759834
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   station_code      345724 non-null  object
 1   measure_datetime  345724 non-null  datetime64[ns, UTC]
 2   data              0 non-null       float64
 3   station_name      14 non-null      object
 4   latitude          14 non-null      float64
 5   longitude         14 non-null      float64
 6   quality_flag      14 non-null      object
 7   basin             14 non-null      object
 8   sub_basin         14 non-null      object
 9   tambon            14 non-null      object
 10  amphoe            14 non-null      object
 11  province          14 non-null      object
 12  data_type         14 non-null      object
 13  day_of_year       345724 non-null  int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 38.2+ MB

**Reasoning**:
Now that the median rainfall values for each station and day of the year have been calculated, the next step is to merge these median values into the `missing_records_df`. This will allow us to impute the missing 'data' values using the appropriate median for each `station_code` and `day_of_year`.

In [62]:
missing_records_filled = pd.merge(
    missing_records_df[['station_code', 'measure_datetime', 'day_of_year']],
    median_rainfall_by_day,
    on=['station_code', 'day_of_year'],
    how='left',
    suffixes=('_missing', '_median')
)

# Rename the 'data_median' column to 'data' to represent the filled values
missing_records_filled.rename(columns={'data_median': 'data'}, inplace=True)

# Fill other columns that are missing in missing_records_df with information from hill_daily_rain_cleaned
# This can be done by merging with hill_daily_rain_cleaned on station_code, and then filling NaN values
# For simplicity, we can get station-specific static details from the original dataframe.
station_details = hill_daily_rain_cleaned[['station_code', 'station_name', 'latitude', 'longitude', 'quality_flag', 'basin', 'sub_basin', 'tambon', 'amphoe', 'province', 'data_type']].drop_duplicates(subset=['station_code'])
missing_records_filled = pd.merge(missing_records_filled, station_details, on='station_code', how='left', suffixes=('_filled', ''))

print("ข้อมูลบันทึกที่หายไปที่ถูกเติมค่าแล้ว (5 แถวแรก):")
display(missing_records_filled.head())
print("ประเภทข้อมูลของ missing_records_filled:")
missing_records_filled.info()

ข้อมูลบันทึกที่หายไปที่ถูกเติมค่าแล้ว (5 แถวแรก):

,station_code,measure_datetime,day_of_year,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ACRU,2012-01-02 00:00:00+00:00,2,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
1,ACRU,2012-01-03 00:00:00+00:00,3,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
2,ACRU,2012-01-04 00:00:00+00:00,4,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3,ACRU,2012-01-05 00:00:00+00:00,5,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
4,ACRU,2012-10-31 00:00:00+00:00,305,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

ประเภทข้อมูลของ missing_records_filled:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345724 entries, 0 to 345723
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   station_code      345724 non-null  object
 1   measure_datetime  345724 non-null  datetime64[ns, UTC]
 2   day_of_year       345724 non-null  int32
 3   data              345724 non-null  float64
 4   station_name      345724 non-null  object
 5   latitude          345724 non-null  float64
 6   longitude         345724 non-null  float64
 7   quality_flag      345724 non-null  object
 8   basin             345724 non-null  object
 9   sub_basin         345724 non-null  object
 10  tambon            345724 non-null  object
 11  amphoe            345724 non-null  object
 12  province          345724 non-null  object
 13  data_type         345724 non-null  object
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 35.6+ MB

## เติมข้อมูลปริมาณน้ำฝนที่หายไป

### Subtask:
นำค่ามัธยฐานที่คำนวณได้จาก 'median_rainfall_by_day' มาเติมลงในช่องว่าง (NaN) ของคอลัมน์ 'data' ที่เป็น record ที่หายไปใน `missing_records_df` โดยจับคู่ตาม 'station_code' และ 'day_of_year'

**เหตุผล:** ตอนนี้เรามีค่ามัธยฐานของปริมาณน้ำฝนสำหรับแต่ละสถานีและแต่ละวันในรอบปีแล้ว ขั้นตอนต่อไปคือการนำค่ามัธยฐานเหล่านี้มาใช้เติมเต็มข้อมูลที่หายไปใน `missing_records_df` ซึ่งจะช่วยให้ข้อมูลมีความสมบูรณ์ยิ่งขึ้นสำหรับการวิเคราะห์ต่อไป

In [63]:
missing_records_filled = pd.merge(
    missing_records_df[['station_code', 'measure_datetime', 'day_of_year']],
    median_rainfall_by_day,
    on=['station_code', 'day_of_year'],
    how='left',
    suffixes=('_missing', '_median')
)

# Rename the 'data_median' column to 'data' to represent the filled values
missing_records_filled.rename(columns={'data_median': 'data'}, inplace=True)

# Fill other columns that are missing in missing_records_df with information from hill_daily_rain_cleaned
# This can be done by merging with hill_daily_rain_cleaned on station_code, and then filling NaN values
# For simplicity, we can get station-specific static details from the original dataframe.
station_details = hill_daily_rain_cleaned[['station_code', 'station_name', 'latitude', 'longitude', 'quality_flag', 'basin', 'sub_basin', 'tambon', 'amphoe', 'province', 'data_type']].drop_duplicates(subset=['station_code'])
missing_records_filled = pd.merge(missing_records_filled, station_details, on='station_code', how='left', suffixes=('_filled', ''))

print("ข้อมูลบันทึกที่หายไปที่ถูกเติมค่าแล้ว (5 แถวแรก):")
display(missing_records_filled.head())
print("ประเภทข้อมูลของ missing_records_filled:")
missing_records_filled.info()

ข้อมูลบันทึกที่หายไปที่ถูกเติมค่าแล้ว (5 แถวแรก):

,station_code,measure_datetime,day_of_year,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ACRU,2012-01-02 00:00:00+00:00,2,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
1,ACRU,2012-01-03 00:00:00+00:00,3,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
2,ACRU,2012-01-04 00:00:00+00:00,4,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3,ACRU,2012-01-05 00:00:00+00:00,5,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
4,ACRU,2012-10-31 00:00:00+00:00,305,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

ประเภทข้อมูลของ missing_records_filled:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345724 entries, 0 to 345723
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   station_code      345724 non-null  object
 1   measure_datetime  345724 non-null  datetime64[ns, UTC]
 2   day_of_year       345724 non-null  int32
 3   data              345724 non-null  float64
 4   station_name      345724 non-null  object
 5   latitude          345724 non-null  float64
 6   longitude         345724 non-null  float64
 7   quality_flag      345724 non-null  object
 8   basin             345724 non-null  object
 9   sub_basin         345724 non-null  object
 10  tambon            345724 non-null  object
 11  amphoe            345724 non-null  object
 12  province          345724 non-null  object
 13  data_type         345724 non-null  object
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 35.6+ MB

In [44]:
combined_df = pd.concat([hill_daily_rain_cleaned, missing_records_filled], ignore_index=True)

# Sort the combined DataFrame to ensure chronological order for each station
combined_df.sort_values(by=['station_code', 'measure_datetime'], inplace=True)

# Reset index after sorting
combined_df.reset_index(drop=True, inplace=True)

# Ensure 'day_of_year' is present in the final combined dataframe
combined_df['day_of_year'] = combined_df['measure_datetime'].dt.dayofyear

print("ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวแรก):\n")
display(combined_df.head())
print("ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวสุดท้าย):\n")
display(combined_df.tail())
print("ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled:\n")
print(combined_df['data'].isnull().sum())
print("ประเภทข้อมูลของ hill_daily_rain_filled:\n")
combined_df.info()

ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
0,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
1,ACRU,2012-01-02 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2
2,ACRU,2012-01-03 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,3
3,ACRU,2012-01-04 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,4
4,ACRU,2012-01-05 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,5

ข้อมูล hill_daily_rain_filled ที่รวมและเติมค่าแล้ว (5 แถวสุดท้าย):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
2004246,YOM012,2024-11-26 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,331
2004247,YOM012,2024-11-27 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004248,YOM012,2024-11-27 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004249,YOM012,2024-11-28 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333
2004250,YOM012,2024-11-28 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333

ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled:

16
ประเภทข้อมูลของ hill_daily_rain_filled:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004251 entries, 0 to 2004250
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  day_of_year       int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 206.4+ MB

**Reasoning**:
The previous step showed 16 remaining nulls in the 'data' column of `combined_df`. This indicates that for some `station_code` and `day_of_year` combinations, a median value could not be computed from the `hill_daily_rain_cleaned` data (likely because all data for those specific combinations were missing initially or very sparse). To fully impute these remaining nulls, I will fill them with the median rainfall for their respective `day_of_year` across all stations. This provides a broader imputation value when a station-specific, day-of-year median is unavailable.

In [45]:
import numpy as np

# Calculate the global median rainfall for each day of the year
global_daily_median = combined_df.groupby('day_of_year')['data'].median().reset_index()
global_daily_median.rename(columns={'data': 'global_median_data'}, inplace=True)

# Merge global median back to combined_df for imputation
combined_df = pd.merge(combined_df, global_daily_median, on='day_of_year', how='left')

# Fill remaining NaN values in 'data' column with the global_median_data
combined_df['data'].fillna(combined_df['global_median_data'], inplace=True)

# Drop the temporary 'global_median_data' column
combined_df.drop(columns=['global_median_data'], inplace=True)


print("ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวแรก):\n")
display(combined_df.head())
print("ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวสุดท้าย):\n")
display(combined_df.tail())
print("ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled หลังเติมเต็มอีกครั้ง:\n")
print(combined_df['data'].isnull().sum())
print("ประเภทข้อมูลของ hill_daily_rain_filled:\n")
combined_df.info()

/tmp/ipython-input-64658185.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_df['data'].fillna(combined_df['global_median_data'], inplace=True)

ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
0,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
1,ACRU,2012-01-02 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2
2,ACRU,2012-01-03 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,3
3,ACRU,2012-01-04 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,4
4,ACRU,2012-01-05 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,5

ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวสุดท้าย):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
2004246,YOM012,2024-11-26 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,331
2004247,YOM012,2024-11-27 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004248,YOM012,2024-11-27 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004249,YOM012,2024-11-28 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333
2004250,YOM012,2024-11-28 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333

ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled หลังเติมเต็มอีกครั้ง:

0
ประเภทข้อมูลของ hill_daily_rain_filled:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004251 entries, 0 to 2004250
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  day_of_year       int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 206.4+ MB

**Reasoning**:
The previous code generated a `FutureWarning` because it used `inplace=True` on a chained assignment with `fillna`. To avoid this warning and ensure modifications are applied correctly, I will directly assign the result of `fillna` back to the 'data' column.

In [46]:
import numpy as np

# Calculate the global median rainfall for each day of the year
global_daily_median = combined_df.groupby('day_of_year')['data'].median().reset_index()
global_daily_median.rename(columns={'data': 'global_median_data'}, inplace=True)

# Merge global median back to combined_df for imputation
combined_df = pd.merge(combined_df, global_daily_median, on='day_of_year', how='left')

# Fill remaining NaN values in 'data' column with the global_median_data
combined_df['data'] = combined_df['data'].fillna(combined_df['global_median_data'])

# Drop the temporary 'global_median_data' column
combined_df.drop(columns=['global_median_data'], inplace=True)


print("ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวแรก):\n")
display(combined_df.head())
print("ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวสุดท้าย):\n")
display(combined_df.tail())
print("ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled หลังเติมเต็มอีกครั้ง:\n")
print(combined_df['data'].isnull().sum())
print("ประเภทข้อมูลของ hill_daily_rain_filled:\n")
combined_df.info()

ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวแรก):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
0,ACRU,2012-01-01 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,1
1,ACRU,2012-01-02 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2
2,ACRU,2012-01-03 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,3
3,ACRU,2012-01-04 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,4
4,ACRU,2012-01-05 00:00:00+00:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,5

ข้อมูล hill_daily_rain_filled หลังเติมค่าที่เหลือด้วยค่ามัธยฐานทั่วโลก (5 แถวสุดท้าย):

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,day_of_year
2004246,YOM012,2024-11-26 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,331
2004247,YOM012,2024-11-27 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004248,YOM012,2024-11-27 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,332
2004249,YOM012,2024-11-28 00:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,U,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333
2004250,YOM012,2024-11-28 17:00:00+00:00,0.0,เมืองสุโขทัย,17.02126,99.81971,N,ยม,แม่น้ำยมตอนล่างส่วนที่ 3,ธานี,เมืองสุโขทัย,สุโขทัย,rainfall_daily,333

ตรวจสอบค่าว่างในคอลัมน์ 'data' ของ hill_daily_rain_filled หลังเติมเต็มอีกครั้ง:

0
ประเภทข้อมูลของ hill_daily_rain_filled:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004251 entries, 0 to 2004250
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC]
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  day_of_year       int32
dtypes: datetime64[ns, UTC](1), float64(3), int32(1), object(9)
memory usage: 206.4+ MB

## ตรวจสอบความสมบูรณ์ของข้อมูลอีกครั้ง

### Subtask:
หลังจากเติมค่าที่หายไปแล้ว ให้ทำการตรวจสอบความสมบูรณ์ของข้อมูลอีกครั้ง เพื่อยืนยันว่าไม่มี record ที่หายไปแล้ว และความสมบูรณ์ของข้อมูลเป็น 100%

In [47]:
print("ตรวจสอบจำนวนค่าว่างในคอลัมน์ 'data' ของ combined_df หลังเติมค่าทั้งหมด:")
print(combined_df['data'].isnull().sum())

print("\nจำนวนสถานีที่ไม่ซ้ำกันใน combined_df:")
print(combined_df['station_code'].nunique())

print("\nจำนวนแถวทั้งหมดใน combined_df หลังจากเติมค่า:")
print(len(combined_df))

ตรวจสอบจำนวนค่าว่างในคอลัมน์ 'data' ของ combined_df หลังเติมค่าทั้งหมด:
0

จำนวนสถานีที่ไม่ซ้ำกันใน combined_df:
384

จำนวนแถวทั้งหมดใน combined_df หลังจากเติมค่า:
2004251

### อภิปราย เหตุใดใช้ Median แทน mean

ในการเติมข้อมูลปริมาณน้ำฝนที่หายไป ผมเลือกใช้ ค่ามัธยฐาน (Median) แทน ค่าเฉลี่ย (Mean) ด้วยเหตุผลหลักๆ ดังนี้:

1.ความทนทานต่อค่าผิดปกติ (Robustness to Outliers): ข้อมูลปริมาณน้ำฝนมักจะมีค่าผิดปกติ (Outliers) เช่น วันที่ฝนตกหนักมากเป็นพิเศษ หรือวันที่ไม่มีฝนเลย (ค่าศูนย์) ซึ่งค่าเหล่านี้สามารถดึงค่าเฉลี่ยให้ผิดเพี้ยนไปได้มาก ในขณะที่ค่ามัธยฐานจะมีความทนทานต่อค่าผิดปกติเหล่านี้มากกว่า เนื่องจากเป็นค่ากลางที่แบ่งข้อมูลออกเป็นสองส่วนเท่าๆ กัน จึงได้รับผลกระทบจากค่าสุดโต่งน้อยกว่า

2.การกระจายของข้อมูลที่ไม่เป็นแบบปกติ (Skewed Distribution): ข้อมูลปริมาณน้ำฝนมักจะมีการกระจายตัวที่ไม่สมมาตร (Skewed) คือมีวันที่มีฝนตกน้อยหรือไม่มีเลยจำนวนมาก และมีวันที่ฝนตกหนักจำนวนน้อยกว่า สำหรับข้อมูลที่มีการกระจายตัวแบบนี้ ค่ามัธยฐานจะสะท้อนค่ากลางของข้อมูลได้ดีกว่าและแม่นยำกว่าค่าเฉลี่ย ซึ่งอาจถูกดึงไปทางค่าที่สูงกว่าในกรณีที่มีฝนตกหนักมากๆ

3.ความหมายทางกายภาพ (Physical Meaning): การใช้ค่ามัธยฐานช่วยให้มั่นใจได้ว่าค่าที่เติมเข้าไปนั้นเป็นค่าที่ 'ทั่วไป' หรือ 'ปกติ' ที่สุดของปริมาณน้ำฝนสำหรับวันนั้นๆ และสถานีนั้นๆ โดยไม่ถูกบิดเบือนจากเหตุการณ์ฝนตกหนักที่เกิดขึ้นไม่บ่อยนัก ทำให้การประมาณค่ามีความสมเหตุสมผลมากขึ้น  

การใช้ Median จึงเป็นวิธีการที่ "ปลอดภัยกว่า" (Conservative) และ "ทนทาน" (Robust) ต่อข้อมูลที่ผิดปกติ เหมาะสำหรับการสร้างข้อมูลตัวแทน (Representative Data) เพื่อนำไปรันโมเดลที่ไม่ต้องการให้ค่า Extreme มาบิดเบือนผลลัพธ์ในภาพรวม

In [67]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### อ่านไฟล์ CSV ทั้งหมดจากโฟลเดอร์

In [69]:
import os
import pandas as pd

# Define the folder path where the 31 CSV files are located
# Assuming the files are in a folder similar to the previous context, e.g., '/content/drive/MyDrive/midterm.2/07_2025'
# Please change 'path_to_your_folder' to the actual path of your folder containing the 31 files.
folder_path = '/content/drive/MyDrive/midterm.2/07_2025'

# List all files in the folder
all_files = os.listdir(folder_path)

# Filter for CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]

# Check if there are 31 CSV files
if len(csv_files) != 31:
    print(f"Warning: Expected 31 CSV files, but found {len(csv_files)}.")

data_list = []

# Loop through each CSV file and read it into a DataFrame
for filename in csv_files:
    file_path = os.path.join(folder_path, filename)
    try:
        df = pd.read_csv(file_path)
        data_list.append(df)
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,2.6,372,NTTI,2025-07-25
1,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,2.8,572,CMSG,2025-07-25
2,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,28.8,1198298,PIN008,2025-07-25
3,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,0.0,667,NAN006,2025-07-25
4,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,0.0,117,RAY004,2025-07-25

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27875 entries, 0 to 27874
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rainfall_datetime       27875 non-null  object
 1   rainfall_datetime_calc  27875 non-null  object
 2   rainfall_value          27875 non-null  float64
 3   tele_station_id         27875 non-null  int64
 4   tele_station_oldcode    27447 non-null  object
 5   measure_datetime        27875 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.3+ MB

In [70]:
import os
import pandas as pd

# Define the folder path where the 31 CSV files are located
# Assuming the files are in a folder similar to the previous context, e.g., '/content/drive/MyDrive/midterm.2/07_2025'
# Please change 'path_to_your_folder' to the actual path of your folder containing the 31 files.
folder_path = '/content/drive/MyDrive/midterm.2/08_2025'

# List all files in the folder
all_files = os.listdir(folder_path)

# Filter for CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]



data_list = []

# Loop through each CSV file and read it into a DataFrame
for filename in csv_files:
    file_path = os.path.join(folder_path, filename)
    try:
        df = pd.read_csv(file_path)
        data_list.append(df)
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
0,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,0.0,61.0,LBI002,2025-08-14,NaN,NaN
1,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,39.6,62.0,LNR1,2025-08-14,NaN,NaN
2,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,3.8,64.0,NMKH,2025-08-14,NaN,NaN
3,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,0.6,415.0,CGDO,2025-08-14,NaN,NaN
4,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,0.0,414.0,CHM004,2025-08-14,NaN,NaN

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29183 entries, 0 to 29182
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rainfall_datetime       27915 non-null  object
 1   rainfall_datetime_calc  27915 non-null  object
 2   rainfall_value          27912 non-null  float64
 3   tele_station_id         26647 non-null  float64
 4   tele_station_oldcode    27351 non-null  object
 5   measure_datetime        29183 non-null  object
 6   station_code            1268 non-null   object
 7   value                   1268 non-null   float64
dtypes: float64(3), object(5)
memory usage: 1.8+ MB

In [73]:
import os
import pandas as pd

# Define the folder path where the 31 CSV files are located
# Assuming the files are in a folder similar to the previous context, e.g., '/content/drive/MyDrive/midterm.2/07_2025'
# Please change 'path_to_your_folder' to the actual path of your folder containing the 31 files.
folder_path = '/content/drive/MyDrive/midterm.2/09_2025'

# List all files in the folder
all_files = os.listdir(folder_path)

# Filter for CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]



data_list = []

# Loop through each CSV file and read it into a DataFrame
for filename in csv_files:
    file_path = os.path.join(folder_path, filename)
    try:
        df = pd.read_csv(file_path)
        data_list.append(df)
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
0,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,0.0,335.0,KON004,2025-09-18,NaN,NaN
1,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,15.6,693.0,PAS001,2025-09-18,NaN,NaN
2,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,5.0,636.0,PPCT,2025-09-18,NaN,NaN
3,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,3.8,307.0,WEI011,2025-09-18,NaN,NaN
4,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,0.0,58.0,CPY008,2025-09-18,NaN,NaN

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30342 entries, 0 to 30341
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rainfall_datetime       27796 non-null  object
 1   rainfall_datetime_calc  27796 non-null  object
 2   rainfall_value          27796 non-null  float64
 3   tele_station_id         25250 non-null  float64
 4   tele_station_oldcode    26565 non-null  object
 5   measure_datetime        30342 non-null  object
 6   station_code            2546 non-null   object
 7   value                   2546 non-null   float64
dtypes: float64(3), object(5)
memory usage: 1.9+ MB

In [74]:
import os
import pandas as pd

# Define the folder path where the 31 CSV files are located
# Assuming the files are in a folder similar to the previous context, e.g., '/content/drive/MyDrive/midterm.2/07_2025'
# Please change 'path_to_your_folder' to the actual path of your folder containing the 31 files.
folder_path = '/content/drive/MyDrive/midterm.2/10_2025'

# List all files in the folder
all_files = os.listdir(folder_path)

# Filter for CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]



data_list = []

# Loop through each CSV file and read it into a DataFrame
for filename in csv_files:
    file_path = os.path.join(folder_path, filename)
    try:
        df = pd.read_csv(file_path)
        data_list.append(df)
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,385581,TBW014,2025-10-23
1,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,722,POCG,2025-10-23
2,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,839,VLGE17,2025-10-23
3,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,558,HSYO,2025-10-23
4,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,674,WGTG,2025-10-23

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29515 entries, 0 to 29514
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rainfall_datetime       29515 non-null  object
 1   rainfall_datetime_calc  29515 non-null  object
 2   rainfall_value          29514 non-null  float64
 3   tele_station_id         29515 non-null  int64
 4   tele_station_oldcode    27332 non-null  object
 5   measure_datetime        29515 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.4+ MB

In [75]:
import os
import pandas as pd

# Define the folder path where the 31 CSV files are located
# Assuming the files are in a folder similar to the previous context, e.g., '/content/drive/MyDrive/midterm.2/07_2025'
# Please change 'path_to_your_folder' to the actual path of your folder containing the 31 files.
folder_path = '/content/drive/MyDrive/midterm.2/11_2025'

# List all files in the folder
all_files = os.listdir(folder_path)

# Filter for CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]



data_list = []

# Loop through each CSV file and read it into a DataFrame
for filename in csv_files:
    file_path = os.path.join(folder_path, filename)
    try:
        df = pd.read_csv(file_path)
        data_list.append(df)
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,492367,ATG171,2025-11-22
1,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,119.6,901,PAT002,2025-11-22
2,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,278,TKPP,2025-11-22
3,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,479234,TBW026,2025-11-22
4,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,378,VLGE39,2025-11-22

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31086 entries, 0 to 31085
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rainfall_datetime       31086 non-null  object
 1   rainfall_datetime_calc  31086 non-null  object
 2   rainfall_value          31086 non-null  float64
 3   tele_station_id         31086 non-null  int64
 4   tele_station_oldcode    28890 non-null  object
 5   measure_datetime        31086 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.4+ MB

In [76]:
import os
import pandas as pd

# Define the folder path where the 31 CSV files are located
# Assuming the files are in a folder similar to the previous context, e.g., '/content/drive/MyDrive/midterm.2/07_2025'
# Please change 'path_to_your_folder' to the actual path of your folder containing the 31 files.
folder_path = '/content/drive/MyDrive/midterm.2/12_2025'

# List all files in the folder
all_files = os.listdir(folder_path)

# Filter for CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]



data_list = []

# Loop through each CSV file and read it into a DataFrame
for filename in csv_files:
    file_path = os.path.join(folder_path, filename)
    try:
        df = pd.read_csv(file_path)
        data_list.append(df)
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,435372,TBR016,2025-12-23
1,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,1109543,ONE054,2025-12-23
2,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,479220,TBR021,2025-12-23
3,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,865,TNG002,2025-12-23
4,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,12481,STU002,2025-12-23

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32699 entries, 0 to 32698
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rainfall_datetime       32699 non-null  object
 1   rainfall_datetime_calc  32699 non-null  object
 2   rainfall_value          32699 non-null  float64
 3   tele_station_id         32699 non-null  int64
 4   tele_station_oldcode    30436 non-null  object
 5   measure_datetime        32699 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.5+ MB

In [78]:
output_mounthly_rainfall = pd.read_csv('/content/drive/MyDrive/midterm.2/Y_monthly_rain_HII_operation.csv')
output_mounthly_rainfall.head()

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

[link text](https://)
สรุปผลและจัดรูปแบบปริมาณน้ำฝนรายเดือนของปี 2025 (เดือน 7-12) โดยการอ่านไฟล์ CSV ทั้งหมดจากโฟลเดอร์ `/content/drive/MyDrive/midterm.2/07_2025`, `/content/drive/MyDrive/midterm.2/08_2025`, `/content/drive/MyDrive/midterm.2/09_2025`, `/content/drive/MyDrive/midterm.2/10_2025`, `/content/drive/MyDrive/midterm.2/11_2025`, และ `/content/drive/MyDrive/midterm.2/12_2025` มารวมเป็น DataFrame เดียวชื่อ `combined_daily_rain_2025` จากนั้นแปลงคอลัมน์ 'measure_datetime' ให้เป็นรูปแบบ datetime สร้างคอลัมน์ 'month' และ 'year' ขึ้นมา และคำนวณผลรวมปริมาณน้ำฝนรายเดือนโดยจัดกลุ่มด้วย 'tele_station_oldcode', 'year' และ 'month' สุดท้ายจัดรูปแบบชื่อคอลัมน์ให้เป็น 'Node', 'rain', 'month', 'year' เพื่อให้ตรงกับ `output_mounthly_rainfall.csv` และแสดง 5 แถวแรกของ DataFrame ผลลัพธ์พร้อมตรวจสอบประเภทข้อมูล

## รวมข้อมูลฝนรายวันปี 2025 (เดือน 7-12)

### Subtask:
อ่านไฟล์ CSV ทั้งหมดจากโฟลเดอร์ `/content/drive/MyDrive/midterm.2/07_2025` ถึง `/content/drive/MyDrive/midterm.2/12_2025` และรวมเป็น DataFrame เดียวชื่อ `combined_daily_rain_2025`

**Reasoning**:
I need to consolidate all daily rainfall data for 2025 (months 7-12) into a single DataFrame. The previous cells read files from individual month folders one by one, overwriting `combined_daily_rain_2025` each time. To correctly combine all data, I will create a list of all relevant folder paths, iterate through them, read all CSV files within each folder, and then concatenate all resulting DataFrames into one, named `combined_daily_rain_2025`. I will also print its head and info to verify the consolidation.

In [89]:
import os
import pandas as pd

# Define the base path for the monthly folders
base_folder_path = '/content/drive/MyDrive/midterm.2/'

# Create a list of folder paths for months 07 to 12 of 2025
folder_paths = [os.path.join(base_folder_path, f'{month:02d}_2025') for month in range(7, 13)]

data_list = []

# Loop through each folder path
for folder_path in folder_paths:
    # List all files in the current folder
    all_files = os.listdir(folder_path)

    # Filter for CSV files
    csv_files = [f for f in all_files if f.endswith('.csv')]

    # Loop through each CSV file and read it into a DataFrame
    for filename in csv_files:
        file_path = os.path.join(folder_path, filename)
        try:
            df = pd.read_csv(file_path)
            data_list.append(df)
        except Exception as e:
            print(f"Error reading {filename}: {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if data_list:
    combined_daily_rain_2025 = pd.concat(data_list, ignore_index=True)
    print("ข้อมูลที่รวมกันแล้ว (5 แถวแรก):\n")
    display(combined_daily_rain_2025.head())
    print("\nข้อมูลของ DataFrame ที่รวมกันแล้ว:")
    combined_daily_rain_2025.info()
else:
    print("ไม่พบไฟล์ CSV ที่จะนำมารวม หรือเกิดข้อผิดพลาดในการอ่านไฟล์")

ข้อมูลที่รวมกันแล้ว (5 แถวแรก):

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
0,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,2.6,372.0,NTTI,2025-07-25,NaN,NaN
1,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,2.8,572.0,CMSG,2025-07-25,NaN,NaN
2,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,28.8,1198298.0,PIN008,2025-07-25,NaN,NaN
3,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,0.0,667.0,NAN006,2025-07-25,NaN,NaN
4,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,0.0,117.0,RAY004,2025-07-25,NaN,NaN

ข้อมูลของ DataFrame ที่รวมกันแล้ว:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180700 entries, 0 to 180699
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        180700 non-null  object
 6   station_code            3814 non-null    object
 7   value                   3814 non-null    float64
dtypes: float64(3), object(5)
memory usage: 11.0+ MB

**Reasoning**:
I need to process the combined daily rainfall data for 2025. This involves converting the 'measure_datetime' column to a datetime format, extracting the month and year, calculating the monthly rainfall totals, and then renaming the columns to match the target format of 'Node', 'rain', 'month', 'year'. Finally, I will display the first few rows and the data types of the resulting DataFrame for verification.

In [90]:
import pandas as pd

# Convert 'measure_datetime' to datetime objects
# Using errors='coerce' to handle any unparseable dates by setting them to NaT
combined_daily_rain_2025['measure_datetime'] = pd.to_datetime(combined_daily_rain_2025['measure_datetime'], errors='coerce')

# Drop rows where 'measure_datetime' could not be converted (if any)
combined_daily_rain_2025.dropna(subset=['measure_datetime'], inplace=True)

# Create 'month' and 'year' columns
combined_daily_rain_2025['month'] = combined_daily_rain_2025['measure_datetime'].dt.month
combined_daily_rain_2025['year'] = combined_daily_rain_2025['measure_datetime'].dt.year

# Calculate monthly rainfall totals
# Group by 'tele_station_oldcode', 'year', 'month' and sum 'rainfall_value'
monthly_rainfall_2025 = combined_daily_rain_2025.groupby(['tele_station_oldcode', 'year', 'month'])['rainfall_value'].sum().reset_index()

# Rename columns to match the desired format ('Node', 'rain', 'month', 'year')
monthly_rainfall_2025.rename(columns={'tele_station_oldcode': 'Node', 'rainfall_value': 'rain'}, inplace=True)

print("ข้อมูลปริมาณน้ำฝนรายเดือนปี 2025 (5 แถวแรก):")
display(monthly_rainfall_2025.head())
print("\nประเภทข้อมูลของ DataFrame ปริมาณน้ำฝนรายเดือน:")
monthly_rainfall_2025.info()

ข้อมูลปริมาณน้ำฝนรายเดือนปี 2025 (5 แถวแรก):

   Node  year  month   rain
0  ABRT  2025     10   18.0
1  ABRT  2025     11   21.0
2  ABRT  2025     12    0.0
3  ACRU  2025      7   83.0
4  ACRU  2025      8  164.8

ประเภทข้อมูลของ DataFrame ปริมาณน้ำฝนรายเดือน:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6577 entries, 0 to 6576
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    6577 non-null   object
 1   year    6577 non-null   int32
 2   month   6577 non-null   int32
 3   rain    6577 non-null   float64
dtypes: float64(1), int32(2), object(1)
memory usage: 154.3+ KB

### บันทึกผลลัพธ์ปริมาณน้ำฝนรายเดือนปี 2025 ลงในไฟล์ CSV

In [92]:
output_path = '/content/drive/MyDrive/midterm.2/monthly_rainfall_2025.csv'
monthly_rainfall_2025.to_csv(output_path, index=False)
print(f"บันทึกข้อมูลปริมาณน้ำฝนรายเดือนลงใน: {output_path} เรียบร้อยแล้ว")

บันทึกข้อมูลปริมาณน้ำฝนรายเดือนลงใน: /content/drive/MyDrive/midterm.2/monthly_rainfall_2025.csv เรียบร้อยแล้ว

### ผลลัพธ์ปริมาณน้ำฝนรายเดือนสำหรับปี 2025 (เดือน 7-12) ที่จัดรูปแบบแล้ว

In [91]:
display(monthly_rainfall_2025)

        Node  year  month   rain
0       ABRT  2025     10   18.0
1       ABRT  2025     11   21.0
2       ABRT  2025     12    0.0
3       ACRU  2025      7   83.0
4       ACRU  2025      8  164.8
...      ...   ...    ...    ...
6572  YOM016  2025      8  271.0
6573  YOM016  2025      9  172.4
6574  YOM016  2025     10   23.6
6575  YOM016  2025     11   73.0
6576  YOM016  2025     12    5.4

[6577 rows x 4 columns]

In [93]:
display(monthly_rainfall_2025)

        Node  year  month   rain
0       ABRT  2025     10   18.0
1       ABRT  2025     11   21.0
2       ABRT  2025     12    0.0
3       ACRU  2025      7   83.0
4       ACRU  2025      8  164.8
...      ...   ...    ...    ...
6572  YOM016  2025      8  271.0
6573  YOM016  2025      9  172.4
6574  YOM016  2025     10   23.6
6575  YOM016  2025     11   73.0
6576  YOM016  2025     12    5.4

[6577 rows x 4 columns]

[`Output`](https://drive.google.com/file/d/1En1H8aZtuXQbIMqzQhKzGxeTa-VntMts/view?usp=sharing)

### เปรียบเทียบผลลัพธ์ `monthly_rainfall_2025` กับ `output_mounthly_rainfall`

In [95]:
print("ข้อมูล 'monthly_rainfall_2025' (ผลลัพธ์ที่เราสร้าง):")
display(monthly_rainfall_2025.head())
print(monthly_rainfall_2025.info())

print("\nข้อมูล 'output_mounthly_rainfall' (ไฟล์ต้นฉบับที่คุณต้องการเปรียบเทียบ):")
display(output_mounthly_rainfall.head())
print(output_mounthly_rainfall.info())

ข้อมูล 'monthly_rainfall_2025' (ผลลัพธ์ที่เราสร้าง):

   Node  year  month   rain
0  ABRT  2025     10   18.0
1  ABRT  2025     11   21.0
2  ABRT  2025     12    0.0
3  ACRU  2025      7   83.0
4  ACRU  2025      8  164.8

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6577 entries, 0 to 6576
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    6577 non-null   object
 1   year    6577 non-null   int32
 2   month   6577 non-null   int32
 3   rain    6577 non-null   float64
dtypes: float64(1), int32(2), object(1)
memory usage: 154.3+ KB
None

ข้อมูล 'output_mounthly_rainfall' (ไฟล์ต้นฉบับที่คุณต้องการเปรียบเทียบ):

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    18 non-null     object
 1   rain    18 non-null     float64
 2   month   18 non-null     int64
 3   year    18 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 708.0+ bytes
None

[Google drive](https://drive.google.com/drive/folders/1X0d5dE25loGe9WCs_fmO_ZRYnnVpPNQX?usp=sharing)